name: verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install dependencies
        run: pip3 install -U online-judge-verify-helper

      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
          CPLUS_INCLUDE_PATH: /home/runner/work/compro-library/compro-library/ac-library
        run: |
          echo $CPLUS_INCLUDE_PATH
          ls /home/runner/work/compro-library/compro-library
          oj-verify all
